//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOM_Builder.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BOM_Builder.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap actualizar {
            get {
                object obj = ResourceManager.GetObject("actualizar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://localhost:8080/WebAPI.
        /// </summary>
        internal static string BASE_URL {
            get {
                return ResourceManager.GetString("BASE_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap eliminar {
            get {
                object obj = ResourceManager.GetObject("eliminar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap error {
            get {
                object obj = ResourceManager.GetObject("error", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap floppy_save_icon__23 {
            get {
                object obj = ResourceManager.GetObject("floppy-save-icon--23", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap floppy_save_icon__231 {
            get {
                object obj = ResourceManager.GetObject("floppy-save-icon--231", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CAL20.
        /// </summary>
        internal static string HR_alambre {
            get {
                return ResourceManager.GetString("HR_alambre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 69052.
        /// </summary>
        internal static string HR_perfil_aleta {
            get {
                return ResourceManager.GetString("HR_perfil_aleta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10185.
        /// </summary>
        internal static string HR_perfil_escuadra {
            get {
                return ResourceManager.GetString("HR_perfil_escuadra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10331.
        /// </summary>
        internal static string HR_perfil_marcos {
            get {
                return ResourceManager.GetString("HR_perfil_marcos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 17978.
        /// </summary>
        internal static string HR_perfil_travesaño {
            get {
                return ResourceManager.GetString("HR_perfil_travesaño", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CAL20.
        /// </summary>
        internal static string HRP_alambre {
            get {
                return ResourceManager.GetString("HRP_alambre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 69052.
        /// </summary>
        internal static string HRP_perfil_aleta {
            get {
                return ResourceManager.GetString("HRP_perfil_aleta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10185.
        /// </summary>
        internal static string HRP_perfil_escuadra {
            get {
                return ResourceManager.GetString("HRP_perfil_escuadra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5115.
        /// </summary>
        internal static string HRP_perfil_marcos {
            get {
                return ResourceManager.GetString("HRP_perfil_marcos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 17978.
        /// </summary>
        internal static string HRP_perfil_travesaño {
            get {
                return ResourceManager.GetString("HRP_perfil_travesaño", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Source=IQORA;User Id=IQMS;Password=iqms; Connection Timeout=120;.
        /// </summary>
        internal static string IQORA {
            get {
                return ResourceManager.GetString("IQORA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Source=IQTEST;User Id=IQMS;Password=iqms; Connection Timeout=120;.
        /// </summary>
        internal static string IQTEST {
            get {
                return ResourceManager.GetString("IQTEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IQMSWEBSITE.
        /// </summary>
        internal static string nameApp {
            get {
                return ResourceManager.GetString("nameApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap namm {
            get {
                object obj = ResourceManager.GetObject("namm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iqms.
        /// </summary>
        internal static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap plus {
            get {
                object obj = ResourceManager.GetObject("plus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap plus1 {
            get {
                object obj = ResourceManager.GetObject("plus1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap remplazar {
            get {
                object obj = ResourceManager.GetObject("remplazar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap save {
            get {
                object obj = ResourceManager.GetObject("save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7110.
        /// </summary>
        internal static string SG_perfil_aletas {
            get {
                return ResourceManager.GetString("SG_perfil_aletas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10185.
        /// </summary>
        internal static string SG_perfil_escuadra {
            get {
                return ResourceManager.GetString("SG_perfil_escuadra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10331.
        /// </summary>
        internal static string SG_perfil_marcos {
            get {
                return ResourceManager.GetString("SG_perfil_marcos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1427.
        /// </summary>
        internal static string SG_perfil_travesaños {
            get {
                return ResourceManager.GetString("SG_perfil_travesaños", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap share {
            get {
                object obj = ResourceManager.GetObject("share", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap street {
            get {
                object obj = ResourceManager.GetObject("street", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iqms.
        /// </summary>
        internal static string username {
            get {
                return ResourceManager.GetString("username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ver {
            get {
                object obj = ResourceManager.GetObject("ver", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
